[package]
name = "imezx/warp"
version = "1.1.0-pre2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["node_modules", "docs", ".github", "*.rbxl", "*.rbxmx", "*.rbxml", "*.rbxm", "TestEZ", "test.project.json"]
description = "A rapidly-fast & powerful networking library."

[dependencies]