[package]
name = "imezx/warp"
version = "1.0.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = [
    "node_modules",
    "docs",
    ".github",
]
description = "A very-fast & powerful networking library for Roblox."

[dependencies]
